apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox
        command:
        - sh
        - -c
        - |
          until nslookup nginx-init-svc.default.svc.cluster.local; do
            echo "Waiting for service nginx-init-svc..."
            sleep 2
          done
          echo "Service found!"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
